#!/usr/bin/env php
<?php
// XZ Web Server by Fsb
define('ABSPATH', __DIR__);
if (! \in_array(PHP_SAPI, ['cli', 'micro'])) exit('CLI only');

$copt = getopt("a:b:");
$copt_a = $copt['a'] ?? 'sast';

if ('waf' === $copt_a) {
  $b = $copt['b'] ?? 'all';
  include './module/waf_cnf.php';
  test_waf_dev($b);

} else if ('perf_flush' === $copt_a) {
  include './module/xhprof.php';
  profiler_flush();

} elseif ('perf_run' === $copt_a) {
  $dir = 'C:/xampp/xhprof/xhprof/xhprof_html/';
  chdir($dir);
  if ($pso = popen('php -S localhost:70', 'r')) {
    pclose($pso);
  }

} else if ('sast' === $copt_a) {
  \passthru('php vendor/bin/phpstan analyse -c ps.neon --memory-limit=1G');
}

// curl fix the request so it may sent correct request and this not suitable with CRS tests, too bad this approch is IO blocking and not multi process.
function fetch_url(array $dt): int {
  $url = $dt['url'] ?? '';
  $method = strtolower($dt['method'] ?? 'GET');
  $headers_raw = $dt['headers'] ?? [];
  $data = [];
  $status = 400;
  $headers = '';
  foreach ($headers_raw as $k => $v) {
    $headers .= "{$k}: {$v}\r\n";
  }

  $ctx = [
    'http' => [
      'method' => $method,
      'timeout' => 2,
      'header' => $headers,
    ]
  ];

  if ($method === 'post') {
    $ctx['http']['content'] = http_build_query($data);
  }

  $context = stream_context_create($ctx);
  @file_get_contents($url, false, $context);
  
  if (isset($http_response_header[0])) {
    preg_match('~HTTP/\d+\.\d+\s+(\d+)~', $http_response_header[0], $m);
    $status = (int)$m[1];
  }

  return $status;

  // //post
  // $data = [
  //   'name' => 'john',
  //   'age' => 25
  // ];

  // $context = stream_context_create([
  //     'http' => [
  //         'method' => 'POST',
  //         'header' => "Content-Type: application/x-www-form-urlencoded\r\n",
  //         'content' => http_build_query($data)
  //     ]
  // ]);

  // $response = file_get_contents("http://example.com", false, $context);

  // // post json
  // $data = json_encode([
  //   'name' => 'john',
  //   'age' => 25
  // ]);

  // $context = stream_context_create([
  //     'http' => [
  //         'method' => 'POST',
  //         'header' => "Content-Type: application/json\r\n",
  //         'content' => $data
  //     ]
  // ]);

  // $response = file_get_contents("http://example.com/api", false, $context);

  // // header
  // $headers =
  //   "User-Agent: MyAgent\r\n".
  //   "Accept: application/json\r\n";

  // $context = stream_context_create([
  //     'http' => [
  //         'method' => 'GET',
  //         'header' => $headers
  //     ]
  // ]);
}

function test_waf_dev(string|int $scan_id): void {
  global $crs_ignored_ids, $crs_test_must_http_code_200;

  $tmp = $reqs = [];
  $dt = test_waf_load_tests($scan_id);

  // build array
  foreach ($dt as $dtx) {
    $id = $dtx['rule_id'] ?? 0;
    $tests = $dtx['tests'] ?? [];

    if (\in_array($id, $crs_ignored_ids)) continue;

    foreach ($tests as $test) {
      $test_id = $test['test_id'] ?? 0;
      $desc = \substr(($test['desc'] ?? ''), 0, 40);
      $stages = $test['stages'] ?? [];

      foreach ($stages as $stage) {
        $input = $stage['input'] ?? [];

        $dt = [
          'id' => $id,
          'test_id' => $test_id,
          'desc' => $desc,
          'url' => 'http://localhost:8080'.($input['uri'] ?? ''),
          'method' => $input['method'] ?? 'GET',
          'headers' => $input['headers'] ?? [],
        ];

        $exclude_this = (\in_array($id, $crs_test_must_http_code_200));

        $code = fetch_url($dt);

        if (\in_array($code, [200])) {
          if ($exclude_this) {
            echo "{$dt['id']}|{$dt['test_id']}: {$code} Pass".PHP_EOL;
          } else {
            echo "{$dt['id']}|{$dt['test_id']}|{$dt['desc']}: {$code} [FAILED]".PHP_EOL;

            $tmp[] = [
              'id' => $dt['id'],
              'test_id' => $dt['test_id'],
              'desc' => $dt['desc']
            ];
          }
          
        } else {
          echo "{$dt['id']}|{$dt['test_id']}: {$code} Pass".PHP_EOL;
        }
      }
    }
  }

  // chunk
  // $chunks = array_chunk($reqs, 5);

  // foreach ($chunks as $chunk) {
  //   $id = $chunk['id'] ?? 0;
  //   $exclude_this = (\in_array($id, $crs_test_must_http_code_200));

  //   $code = fetch_url($chunk);

  //   if (\in_array($code, [200])) {
  //     if ($exclude_this) {
  //       echo "{$chunk['id']}|{$chunk['test_id']}: {$code} Pass".PHP_EOL;
  //     } else {
  //       echo "{$chunk['id']}|{$chunk['test_id']}|{$chunk['desc']}: {$code} [FAILED]".PHP_EOL;

  //       $tmp[] = [
  //         'id' => $chunk['id'],
  //         'test_id' => $chunk['test_id'],
  //         'desc' => $chunk['desc']
  //       ];
  //     }
      
  //   } else {
  //     echo "{$chunk['id']}|{$chunk['test_id']}: {$code} Pass".PHP_EOL;
  //   }

    // $mh = curl_multi_init();
    // $chs = [];

    // foreach ($chunk as $k => $r) {
    //   $ch = curl_init();
    //   curl_setopt_array($ch, [
    //     CURLOPT_URL => $r['url'],
    //     CURLOPT_RETURNTRANSFER => true,
    //     CURLOPT_CUSTOMREQUEST => strtoupper($r['method']),
    //     CURLOPT_HTTPHEADER => $r['headers'],
    //     CURLOPT_TIMEOUT => 5,
    //     CURLOPT_NOSIGNAL => 1,
    //   ]);

    //   curl_multi_add_handle($mh, $ch);
    //   $chs[$k] = [$ch, $r];
    // }

    // do {
    //   $status = curl_multi_exec($mh, $running);
    //   curl_multi_select($mh);
    // } while ($running && $status == CURLM_OK);

    // foreach ($chs as [$ch, $meta]) {
    //   $err = curl_errno($ch);
    //   $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    //   $exclude_this = (\in_array($meta['id'], $crs_test_must_http_code_200));

    //   if ($err || \in_array($code, [200])) {
    //     if ($exclude_this) {
    //       echo "{$meta['id']}|{$meta['test_id']}: {$code} Pass".PHP_EOL;
    //     } else {
    //       echo "{$meta['id']}|{$meta['test_id']}|{$meta['desc']}: {$code} [FAILED]".PHP_EOL;
    //       print_r($r);
    //       echo PHP_EOL;

    //       $tmp[] = [
    //         'id' => $meta['id'],
    //         'test_id' => $meta['test_id'],
    //         'desc' => $meta['desc']
    //       ];
    //     }
        
    //   } else {
    //     echo "{$meta['id']}|{$meta['test_id']}: {$code} Pass".PHP_EOL;
    //   }

    //   curl_multi_remove_handle($mh, $ch);
    // }

    // curl_multi_close($mh);
  // }

  if (! empty($tmp)) {
    echo 'FAILED: '.\count($tmp).'/'.\count($reqs).PHP_EOL;
    @file_put_contents('./tmp/failed_tests.json', json_encode($tmp));
  }
}

function test_waf_load_tests(string|int $scan_id): array|bool {
  $dir = './test/';
  $rt = [];
  if ($dh = \opendir($dir)){
    while (($file = \readdir($dh)) !== false){
      if (\in_array($file, ['.', '..'])) continue;

      if ('all' !== $scan_id) {
        if (! str_starts_with($file, $scan_id)) continue;
      }

      $fpath = $dir.$file;
      
      if ('yaml' === \pathinfo($fpath, PATHINFO_EXTENSION)) {
        if ($tmp = test_waf_yml2arr($fpath)) {
          $rt[] = $tmp;
        } else {
          echo 'failed load and read: '.$fpath.PHP_EOL;
        }
      }
    }
    closedir($dh);
  }

  return $rt;
}

function test_waf_yml2arr(string $filename): array|bool {
  $rt = false;
  if (\is_file($filename)) {
    if (\function_exists('yaml_parse_file')) {
      $filen = $filename;
      $rt = yaml_parse_file($filen);
    
    } else {
      echo 'missing yaml extention, get it';
    }
  }
  return $rt;
}