<?php
// XZ Web Server by Fsb
if (! \defined('ABSPATH')) exit(0);

return [
  // [
  //   'id' => 920100, // skipped for now
  //   'phase' => 1,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 5,
  //   'msg' => 'Invalid HTTP Request Line',
  //   'rule' => [
  //     ['w' => ['req_line'], 'rx' => '^(?i)(?:GET /[^#?]*(?:\?[^\s\x0b#]*)?(?:#[^\s\x0b]*)?|(?:CONNECT (?:[0-9]{1,3}\.){3}[0-9]{1,3}(?::[0-9]+)?|[A-Za-z0-9_\-]+:[0-9]+)|OPTIONS \*|[A-Za-z]{3,10}[\s\x0b]+(?:[0-9A-Za-z]{3,7}?://[A-Za-z0-9_\-]*(?::[0-9]+)?/[^#?]*(?:\?[^\s\x0b#]*)?(?:#[^\s\x0b]*)?)?[\s\x0b]+[A-Za-z0-9.\-]+))$', 'not' => true],
  //   ],
  // ],
  [
    'id' => 920120,
    'phase' => 2,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Attempted multipart/form-data bypass',
    'rule' => [
      ['w' => ['files', 'files_names'], 'rx' => '~(?i)^(?:&(?:(?:[acegilnorsuz]acut|[aeiou]grav|[aino]tild)e|[c-elnr-tz]caron|(?:[cgklnr-t]cedi|[aeiouy]um)l|[aceg-josuwy]circ|[au]ring|a(?:mp|pos)|nbsp|oslash);|[^"\';=\x5c])*$~', 'not' => true],
    ],
  ],
  [
    'id' => 920160,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Content-Length HTTP header is not numeric',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'content-length', 'rx' => '~^\d+$~', 'not' => true],
    ],
  ],
  [
    'id' => 920170,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'GET or HEAD Request with Body Content',
    'rule' => [
      ['w' => ['method'], 'in' => ['get', 'head']],
      ['w' => ['header'], 'wpr' => 'content-length', 'not' => true, 'rx' => '~^[0-9]+$~'],
    ],
  ],
  [
    'id' => 920171,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'GET or HEAD Request with Transfer-Encoding',
    'rule' => [
      ['w' => ['method'], 'in' => ['get', 'head']],
      ['w' => ['header'], 'wpr' => 'transfer-encoding', 'not' => true, 'rx' => '~^[0-9]+$~'],
    ],
  ],
  // [
  //   'id' => 920180, // skipped for now
  //   'phase' => 1,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 4,
  //   'msg' => 'POST without Content-Length and Transfer-Encoding headers',
  //   'rule' => [
  //     ['w' => ['within'], 'dunno' => 'HTTP/2 HTTP/2.0 HTTP/3 HTTP/3.0'],
  //     ['w' => ['method'], 'in' => ['post']],
  //     ['w' => ['header'], 'wpr' => 'transfer-encoding', 'not' => true, 'rx' => '~^[0-9]+$~'],
  //   ],
  // ],
  [
    'id' => 920181,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'Content-Length and Transfer-Encoding headers present',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'transfer-encoding', 'eq' => '0'],
      ['w' => ['header'], 'wpr' => 'content-length', 'eq' => '0'],
    ],
  ],
  [
    'id' => 920190,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'Obsolete Request-Range header detected',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'range', 'rx' => '~(\d+)-(\d+)~'],
    ],
  ],
  [
    'id' => 920660,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'Obsolete Request-Range header detected',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'request-range', 'gt' => '0'],
    ],
  ],
  [
    'id' => 920210,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'Multiple/Conflicting Connection Header Data Found',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'connection', 'rx' => '~\b([a-z\-]+)\b\s*,\s*\1\b~i'],
    ],
  ],
  [
    'id' => 920250,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'UTF8 Encoding Abuse Attack Attempt',
    'rule' => [
      ['w' => ['args', 'args_names', 'path'], 'utf' => true],
    ],
  ],
  [
    'id' => 920260,
    'phase' => 2,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 255, 153, 267, 72],
    'score' => 4,
    'msg' => 'Unicode Full/Half Width Abuse Attack Attempt',
    'rule' => [
      ['w' => ['body', 'uri'], 'rx' => '~(?i)%uff[0-9a-f]{2}~'],
    ],
  ],
  [
    'id' => 920270,
    'phase' => 2,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Invalid character in request (null character)',
    'rule' => [
      ['w' => ['uri', 'header', 'args', 'args_names'], 'byte_range' => [1,255]],
    ],
  ],
  [
    'id' => 920280,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Request Missing a Host Header',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'host', 'eq' => '0'],
    ],
  ],
  [
    'id' => 920290,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Request Missing a Host Header',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'host', 'rx' => '~^$~'],
    ],
  ],
  [
    'id' => 920310,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Request Has an Empty Accept Header',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'accept', 'rx' => '~^$~'],
      ['w' => ['method'], 'in' => ['options'], 'not' => true],
      ['w' => ['header'], 'wpr' => 'user-agent', 'rx' => '~AppleWebKit Android Business Enterprise Entreprise~', 'not' => true],
    ],
  ],
  [
    'id' => 920311,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Request Has an Empty Accept Header',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'accept', 'rx' => '~^$~'],
      ['w' => ['method'], 'in' => ['options'], 'not' => true],
      ['w' => ['header'], 'wpr' => 'user-agent', 'eq' => '0'],
    ],
  ],
  [
    'id' => 920330,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 2,
    'msg' => 'Empty User Agent Header',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'user-agent', 'rx' => '~^$~'],
    ],
  ],
  [
    'id' => 920340,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Content-Type header missing from request with non-zero Content-Length',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'content-length', 'rx' => '~^0$~', 'not' => true],
      ['w' => ['header'], 'wpr' => 'content-type', 'eq' => '0'],
    ],
  ],
  [
    'id' => 920350,
    'phase' => 1,
    'pl' => 1,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 4,
    'msg' => 'Content-Type header missing from request with non-zero Content-Length',
     'rule' => [
      ['w' => ['header'], 'wpr' => 'host', 'rx' => '~(?:^([\d.]+|\[[\da-f:]+\]|[\da-f:]+)(:[\d]+)?$)~'],
    ],
  ],
  // [
  //   'id' => 920380, // skipped for now
  //   'phase' => 2,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 5,
  //   'msg' => 'Too many arguments in request',
  //    'rule' => [
  //     ['w' => ['args_num'], 'gt' => 255],
  //   ],
  // ],
  // [
  //   'id' => 920360, // skipped for now
  //   'phase' => 2,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 5,
  //   'msg' => 'Argument name too long',
  //    'rule' => [
  //     ['w' => ['args_names'], 'gt' => 255],
  //   ],
  // ],
  //   'id' => 920370, // skipped for now
  //   'phase' => 2,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 5,
  //   'msg' => 'Argument value too long',
  //    'rule' => [
  //     ['w' => ['args'], 'gt' => 255],
  //   ],
  // ],
  //   'id' => 920390, // skipped for now
  //   'phase' => 2,
  //   'pl' => 1,
  //   'atk_cat' => ['protocol'],
  //   'capec' => [1000, 210, 272],
  //   'score' => 5,
  //   'msg' => 'Total arguments size exceeded',
  //    'rule' => [
  //     ['w' => ['tot_args_leng'], 'gt' => 255],
  //   ],
  // ],
  
  [
    'id' => 920121, 
    'phase' => 2,
    'pl' => 2,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Attempted multipart/form-data bypass',
    'rule' => [
      ['w' => ['files'], 'rx' => '~[\'";=\x5c]~'],
    ],
  ],
  [
    'id' => 920510,
    'phase' => 1,
    'pl' => 3,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 210, 272],
    'score' => 5,
    'msg' => 'Invalid Cache-Control request header',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'cache-control', 'rx' => '^\s*(?:max-age=\d+|s-maxage=\d+|max-stale(?:=\d+)?|min-fresh=\d+|no-cache(?:="?[!#$%&\'*+\-.^_`|~0-9A-Za-z]+\"?)?|no-store|no-transform|only-if-cached|must-revalidate|proxy-revalidate|public|private(?:="?[!#$%&\'*+\-.^_`|~0-9A-Za-z]+\"?)?)(?:\s*,\s*(?:max-age=\d+|s-maxage=\d+|max-stale(?:=\d+)?|min-fresh=\d+|no-cache(?:="?[!#$%&\'*+\-.^_`|~0-9A-Za-z]+\"?)?|no-store|no-transform|only-if-cached|must-revalidate|proxy-revalidate|public|private(?:="?[!#$%&\'*+\-.^_`|~0-9A-Za-z]+\"?)?))*\s*$', 'not'=> true],
    ],
  ],
  [
    'id' => 920521,
    'phase' => 1,
    'pl' => 3,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 255, 153],
    'score' => 5,
    'msg' => 'Invalid character in request headers (outside of very strict set)',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'accept-encoding', 'rx' => '#(?:br|compress|deflate|(?:pack200-)?gzip|identity|\*|aes128gcm|exi|zstd|x-(?:compress|gzip))#i', 'not' => true],
    ],
  ],
  [
    'id' => 920275, // todo
    'phase' => 1,
    'pl' => 4,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 255, 153],
    'score' => 5,
    'msg' => 'Invalid character in request headers (outside of very strict set)',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'sec-fetch-user', 'rx' => '~^(?:\?[01])?$~', 'not' => true],
    ],
  ],
  [
    'id' => 920275,
    'phase' => 1,
    'pl' => 4,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 255, 153],
    'score' => 5,
    'msg' => 'Invalid character in request headers (outside of very strict set)',
    'rule' => [
      ['w' => ['header'], 'wpr' => 'sec-ch-ua-mobile', 'rx' => '~^(?:\?[01])?$~', 'not' => true],
    ],
  ],
  [
    'id' => 920460, // todo
    'phase' => 2,
    'pl' => 4,
    'atk_cat' => ['protocol'],
    'capec' => [1000, 153, 267],
    'score' => 5,
    'msg' => 'Abnormal character escapes in request',
    'rule' => [
      ['w' => ['uri', 'header'], 'rx' => '~(?:^|[^\x5c])\x5c[cdeghijklmpqwxyz123456789]~'],
    ],
  ],
];